---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: deploy restic template
  template:
    src: templates/restic_forget_snapshots.j2
    dest: /opt/restic-backup.sh
    group: "{{ restic_archiver__owner }}"
    owner: "{{ restic_archiver__group }}"
    mode: 0700
  become: true

- include_tasks: logs.yml
  when: restic_archiver__log_output | bool

- include_tasks: cron.yml
